DROP TABLE LAND;
CREATE TABLE LAND (
	landid       INT      NOT NULL 
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name     VARCHAR(45) NOT NULL ,
	PRIMARY KEY (landid)
);

DROP TABLE REGION;
CREATE TABLE REGION (
	RegionID INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	LandID   INT,
	Name     VARCHAR(45),
	PRIMARY KEY (RegionID),
	CONSTRAINT fk_region_land
		FOREIGN KEY ( LandID )
		REFERENCES LAND ( landId )
);

DROP TABLE STADT;
CREATE TABLE STADT (
	StadtID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	RegionID INT,
	Name     VARCHAR(45),
	PRIMARY KEY (StadtID),
	CONSTRAINT fk_stadt_region
		FOREIGN KEY ( RegionID )
		REFERENCES REGION ( RegionID )
);


DROP TABLE SHOP;
CREATE TABLE SHOP (
	ShopID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	StadtID INT,
	Name     VARCHAR(45),
	PRIMARY KEY (ShopID),
	CONSTRAINT fk_shop_stadt
		FOREIGN KEY ( StadtID )
		REFERENCES STADT ( StadtID )
);

#####################################################

DROP TABLE PRODUCTCATEGORY;
CREATE TABLE PRODUCTCATEGORY (
	ProductcategoryID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Name     VARCHAR(45),
	PRIMARY KEY (ProductcategoryID)
);


DROP TABLE PRODUCTFAMILY;
CREATE TABLE PRODUCTFAMILY (
	ProductfamilyID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ProductcategoryID INT,
	Name     VARCHAR(45),
	PRIMARY KEY (ProductfamilyID),
	CONSTRAINT fk_Productfamily_Productcategory
		FOREIGN KEY ( ProductcategoryID )
		REFERENCES PRODUCTCATEGORY ( ProductcategoryID )
);


DROP TABLE PRODUCTGROUP;
CREATE TABLE PRODUCTGROUP (
	ProductGroupID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ProductfamilyID INT,
	Name     VARCHAR(45),
	PRIMARY KEY (ProductGroupID),
	CONSTRAINT fk_ProductGroup_Productfamily
		FOREIGN KEY ( ProductfamilyID )
		REFERENCES PRODUCTFAMILY ( ProductfamilyID )
);


DROP TABLE ARTICLE;
CREATE TABLE ARTICLE (
	ArticleID  INT   NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ProductGroupID INT,
	Name     VARCHAR(45),
	Preis INT,
	PRIMARY KEY (ArticleID),
	CONSTRAINT fk_Article_ProductGroup
		FOREIGN KEY ( ProductGroupID )
		REFERENCES PRODUCTGROUP ( ProductGroupID )
);

#######################################################

DROP TABLE VERKAUFSTABELLE;
CREATE TABLE VERKAUFSTABELLE (
	VerkaufstabelleID INT NOT NULL
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ShopID INT,
	ArtikelID INT,
	Zeit INT,
	Anzahl INT,
	Umsatz INT,
	PRIMARY KEY (ProductfamilyID),
	CONSTRAINT fk_Verkaufstabelle_Shop
		FOREIGN KEY ( ShopID )
		REFERENCES SHOP ( ShopID ),
	CONSTRAINT fk_Verkaufstabelle_Artikel
		FOREIGN KEY ( ArtikelID )
		REFERENCES ARTIKEL ( ArtikelID )
);








